framework:
    messenger:
        transports:
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Messenger\Message\AliasChangeMessage': amqp
            'App\Messenger\Message\AliasSyncingMessage': amqp
