version: '3.7'
services:
    nginx:
        container_name: ellias_nginx
        restart: always
        image: nginx:latest
        depends_on:
            - php
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - traefik_network
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_network"
            - "traefik.http.routers.ellias.entrypoints=websecure"
            - "traefik.http.routers.ellias.rule=Host(`${APP_URL}`)"
            - "traefik.http.routers.ellias.tls=true"
            - "traefik.http.routers.ellias.tls.certresolver=myresolver"
            - "traefik.http.services.ellias.loadbalancer.server.port=80"

    php:
        container_name: ellias_php
        restart: always
        build: docker/php
        volumes:
            - .:/app

networks:
    traefik_network:
        external: true
