version: '2'
services:
    nginx:
        container_name: nginx
        image: nginx:latest
        depends_on:
            - php
        ports:
            - "8000:80"
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    php:
        container_name: php
        build:
            context: docker/php
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - .:/app
    mercure:
        container_name: mercure
        image: dunglas/mercure
        command: caddy run -config /etc/caddy/Caddyfile.dev # Enable demo mode
        environment:
            # You should definitely change all these values in production
            - MERCURE_PUBLISHER_JWT_KEY=!ChangeMe!
            - MERCURE_SUBSCRIBER_JWT_KEY=!ChangeMe!
            - DEBUG=debug
            - SERVER_NAME=:80
            - MERCURE_EXTRA_DIRECTIVES=cors_allowed_origins *\npublish_allowed_origins http://localhost:1337 https://localhost:1338
        ports:
            - "1337:80"
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - 8080:15672
        environment:
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit

