services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Define namespace for DI
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags: [ 'controller.service_arguments' ]

    # Define used provider
    App\Provider\AliasApiInterface: '@App\Provider\Fake\FakeAliasApi'

    # Logger decorator for api call
    App\Provider\AliasApiLoggerDecorator:
        decorates: 'App\Provider\AliasApiInterface'

    ### API Platform configuration

    App\DataPersister\AliasDataPersister:
        decorates: 'api_platform.doctrine.orm.data_persister'
