resources:
    App\Entity\Alias:
        collectionOperations:
            get: ~
            post: ~
        itemOperations:
            get: ~
            delete: ~
            patch:
                denormalization_context:
                    groups: ['update']
