name: quality
on: [push, pull_request]

jobs:
    php-cs-fixer:
        name: php-cs-fixer
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: PHP-CS-Fixer
                uses: OskarStark/php-cs-fixer-ga@2.16.1.2
                with:
                    args: --diff --dry-run
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Validate composer.json and composer.lock
                run: composer validate
            -   name: Install dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
            -   name: Run test suite
                run: composer run-script test
                env:
                    APP_ENV: test
