name: quality
on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: PHP Code Standards Violations Analysis
                run: composer run-script phpcs

            -   name: PHP Static Analysis
                run: composer run-script phpstan

            -   name: Run test suite
                run: composer run-script test
                env:
                    APP_ENV: test
